# Generated by Django 4.2.2 on 2023-06-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_report_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='hours',
            field=models.IntegerField(max_length=2, verbose_name='Количество часов'),
        ),
    ]
