# Generated by Django 4.2.2 on 2023-06-14 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_alter_report_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='hours',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Количество часов'),
        ),
    ]
