# Generated by Django 4.2.2 on 2023-06-15 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_report_text_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name_plural': 'Данные для отчета'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
        migrations.AddField(
            model_name='projects',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
