# Generated by Django 4.2.2 on 2023-06-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_alter_projects_users'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('user', 'project', 'date')},
        ),
    ]
